# Generated by Django 4.2.24 on 2025-09-28 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作者姓名')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='作者简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='图书ISBN编号')),
                ('title', models.CharField(max_length=255, verbose_name='图书标题')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='出版社')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='出版日期')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='图书分类')),
                ('total_copies', models.IntegerField(default=0, verbose_name='总藏书量')),
                ('available_copies', models.IntegerField(default=0, verbose_name='可借数量')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='图书馆位置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=20, unique=True, verbose_name='读者证号')),
                ('name', models.CharField(max_length=100, verbose_name='读者姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=4, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='电子邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='家庭地址')),
                ('register_date', models.DateField(verbose_name='注册日期')),
                ('status', models.CharField(choices=[('正常', '正常'), ('冻结', '冻结')], default='正常', max_length=4, verbose_name='读者状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '读者',
                'verbose_name_plural': '读者',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='借阅日期')),
                ('due_date', models.DateField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还日期')),
                ('status', models.CharField(choices=[('已借出', '已借出'), ('已归还', '已归还'), ('逾期', '逾期')], default='已借出', max_length=4, verbose_name='借阅状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryModel.book', verbose_name='图书')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryModel.reader', verbose_name='读者')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryModel.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryModel.book')),
            ],
            options={
                'verbose_name': '图书作者关联',
                'verbose_name_plural': '图书作者关联',
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', through='LibraryModel.BookAuthor', to='LibraryModel.book'),
        ),
    ]
