# Generated by Django 4.2.24 on 2025-09-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='bookauthor',
            table='book_authors',
        ),
        migrations.AlterModelTable(
            name='borrowrecord',
            table='borrow_records',
        ),
        migrations.AlterModelTable(
            name='reader',
            table='readers',
        ),
    ]
